---
title: "metereological_stations_analyses"
format: html
---

```{r}
# Load library
library(leaflet)
library(ggplot2)
library(plotly)
library(terra)
library(dplyr)
library(lubridate)
```

```{r}
# Read your CSV file
# metereological data
stations <- read.csv("D:/2025_Osa_Conservation/DATA/metereological_stations/station_locations.csv")
# landcover data
ldc <- rast("D:/2025_Osa_Conservation/DATA_YN/data_major_landocvers_LST_comparison/landcover_210_pure_YN_5367_major_landcov.tif")

stations
```

```{r}
# Extract raster values at the points
values_at_points <- terra::extract(ldc, vect(stations, geom = c("Long", "Lat"), crs = "EPSG:4326"))
values_at_points

# Create an interactive map
leaflet(stations) %>%
  addTiles() %>%
  addCircleMarkers(
    lng = ~Long, lat = ~Lat,
    popup = ~paste("<b>", Station, "</b><br>Elevation:", Elev_m, "m"),
    radius = 6,
    color = "blue",
    fillOpacity = 0.7
  ) %>%
  addProviderTiles("CartoDB.Positron")
```

```{r}
max_temp <- read.csv("D:/2025_Osa_Conservation/DATA/metereological_stations/derived/daily_maximum_temp.csv")
max_temp
```

```{r}
colnames(max_temp)
unique(max_temp$location)
```

```{r}
# convert the date column to date data type
max_temp$date <- as.Date(max_temp$date,format = "%Y-%m-%d")
# get entries only for 2023
max_temp_23 <- max_temp[max_temp$date >= as.Date("2023-01-01") & max_temp$date <= as.Date("2023-12-31"), ]
# remove NA values
max_temp_23 <- subset(max_temp_23,!is.na(value))
max_temp_23
# remove outliers
max_temp_23 <- max_temp_23[max_temp_23$value < 38, ]

# plot interactive plot
p <- ggplot(max_temp_23, aes(
  x = date, 
  y = value, 
  color = location, 
  group = location,
  text = paste("Date:", date, 
               "<br>Value:", value, 
               "<br>Location:", location)
)) +
  geom_line() +
  geom_smooth(method = "loess", span = 0.1, se = FALSE, size = 0.5, color = "black") +
  theme_minimal()

ggplotly(p, tooltip = "text")
```

```{r}
# get the hottest day of the month for each location

# order by elevation
stations <- stations %>%
  arrange(Elev_m)

names <- c("Puerto_Jimenez", "Las_Esferas", "Ciudad_Neily","Fundación_Neotropica", "Greg_gund", "San_Vito", "Las_Brisas", "Altamira")

max_temp_23$location <- factor(max_temp_23$location, levels = names)

# Top 3 hottest days per location
top3_days <- max_temp_23 %>%
  group_by(location) %>%
  slice_max(order_by = value, n = 3, with_ties = FALSE) %>%
  ungroup()

top3_days

View(table(top3_days$date))

# Top 3 coldest days per location
bottom3_days <- max_temp_23 %>%
  group_by(location) %>%
  slice_min(order_by = value, n = 3, with_ties = FALSE) %>%
  ungroup()

View(table(bottom3_days$date))

ggplot(max_temp_23, aes(x = date, y = location, fill = value)) +
  geom_tile() +
  geom_point(data = top3_days, aes(x = date, y = location), color = "#e60000", size = 3, shape = 17,inherit.aes = FALSE) +
  geom_point(data = bottom3_days, aes(x = date, y = location), color = "#0066ff", size = 3, shape = 17) +
  scale_fill_viridis_c(option = "plasma") +
  scale_x_date(date_breaks = "1 month",  date_labels = "%b %Y")+
  theme_minimal() +
  labs(
    title = "Daily Temperatures per Station with Top 3 Hottest Days",
    x = "Date",
    y = "Station",
    fill = "Temperature"
  ) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# Compute mean temperature per day
daily_mean <- max_temp_23 %>%
  group_by(date) %>%
  summarize(mean_temp = mean(value, na.rm = TRUE)) %>%
  ungroup()

top3_days <- daily_mean %>%
  slice_max(order_by = mean_temp, n = 10, with_ties = FALSE)
top3_days

# daily_mean is your data frame with date and mean_temp
plot(daily_mean$date, daily_mean$mean_temp,
     type = "l",           # 'l' for line
     col = "red",
     lwd = 2,              # line width
     xlab = "Date",
     ylab = "Mean Temperature",
     main = "Mean Daily Temperature Across All Stations")

```
