---
title: "pairs_timeseries"
format: html
editor_options: 
  chunk_output_type: console
---

source("functions.R")

```{r}
library(lubridate)
library(tidyverse)
library(terra)
library(dplyr)
library(here)
source(here("01_functions","functions.R"))

# for correlation analyses
library(car)
library(GGally)
library(ggplot2)
library(ggpmisc)
```

# RONI index

```{r}
# Read into a tiblle

csv <- read_csv(here("00_data", "raw", "roni.csv"))

colnames(csv)

roni <- csv |>
  rename(
    date = 1,
    roni = 2
  ) |>
  mutate(
    date = as.Date(date),
    roni = na_if(roni, -9999)
  )|> 
  filter(
    date >= as.Date("2020-10-01"), 
    date < as.Date("2024-11-01")
  )
  

roni

ggplot(roni, aes(date,roni))+
  geom_point() +
  scale_x_date(
    date_labels = "%b %Y",
    date_breaks = "3 months",
    date_minor_breaks = "1 month"
    ) + 
    annotate("rect", xmin = as.Date("2023-06-01"), xmax = as.Date("2024-05-01"), ymin = -Inf, ymax = Inf,         alpha = .2
    ) +
    annotate("text", x = as.Date("2024-06-01"), y = 1.5, label = "El Niño"
    ) +
    labs(
      x = "Date", 
      y = "Relative Oceanic Niño Index (°C)") +
    theme(axis.text.x=element_text(angle=45, hjust=1)) 
  
```

# Climate data

```{r}
# ERA 5 Tair at 2m at 13:30 and 01:30 solar time
temp <- read_csv(here("00_data","processed", "t2m_1330_0130_solar_time.csv"))
temp

# Total Precipitation - monthly mean
precip <- read_csv(here("00_data","processed", "monthly_total_precip.csv"))
precip

# Surface short-wave (solar) radiation downwards at 13:30 solar time (ssrd taken for the hour before)
ssrd <- read_csv(here("00_data","processed", "ssrd_1330_solar_time.csv"))
ssrd

```

# LST data

```{r}
monthly_lst <- read_csv(here("00_data", "processed", "lst_cooling_monthly_mean_1330.csv"))

monthly_lst
```

# Join RONI and Climate data and LST

```{r}
# join with the roni table
full <- roni |>
  full_join(temp, by = "date") |>
  full_join(monthly_lst, by = join_by("date" == "month_date")) |>
  full_join(precip, by = "date") |>
  full_join(ssrd, by = "date")

full

write_csv(full, here("04_output", "lst_and_climate_var_monthly_mean.csv"))
```

## Plot join

```{r}

full <- read_csv(here("04_output", "lst_and_climate_var_monthly_mean.csv"))

# First restructure the data
df_long <- full |>
  # select(c(precipitation_mm, roni, ssrd_Wm2_1330, t1330, lst_mean, cooling)) |>
  pivot_longer(
    # cols = c(precipitation_mm, roni, ssrd_Wm2_1330, t1330, lst_mean, cooling),
    cols = c(precipitation_mm, roni, ssrd_Wm2_1330, t1330, lst_mean, cooling),
    names_to = "variable",
    values_to = "value"
  )
df_long

# Factor the variables, to define the order they will appear in the plot
df_long$variable <- factor(
  df_long$variable,
  # levels = c("precipitation_mm", "roni", "ssrd_Wm2_1330", "t1330", "lst_mean", "cooling")
  levels = c("precipitation_mm", "roni", "ssrd_Wm2_1330", "t1330", "lst_mean", "cooling")
)

# Change the names for the plot
df_long$variable <- dplyr::recode(df_long$variable,
                           # t1330 = "Air Temperature (°C)", #at 13:30 local solar time
                           t1330 = "Air Temperature (°C)", #at 01:30 local solar time
                           roni = "Relative Oceanic Niño Index (°C)",
                           precipitation_mm = "Precipitation (mm)",
                           lst_mean = "Land Surface Temperature (°C)", #at 13:30 local solar time
                           ssrd_Wm2_1330 = "Downward short-wave solar radiation (W m⁻²)", #at 13:30 local solar time
                        
                           cooling = "Forest-induced cooling (°C)")


# Then plot with facet wrap
ggplot(df_long, aes(date, value)) +
  geom_point() +
  geom_line() +
  scale_x_date(
    date_labels = "%b %Y",
    date_breaks = "3 months",
    date_minor_breaks = "1 month"
    ) +
    theme(axis.text.x=element_text(angle=45, hjust=1)) +
  facet_wrap(~ variable, scales = "free_y", ncol = 1)
```

## Corellation

```{r}
df <- read_csv(here("04_output", "lst_and_climate_var_monthly_mean.csv"))

#renaming the columns for readability
# names(df)[names(df) == "cooling"] <- "forest_cooling"
names(df)[names(df) == "lst_mean"] <- "lst"
names(df)[names(df) == "t1330"] <- "air_temp"
names(df)[names(df) == "precipitation_mm"] <- "precipitation"
names(df)[names(df) == "ssrd_Wm2_1330"] <- "solar_radiation"

# Create a group variable
df$period <- ifelse(df$date >= "2023-03-01" & df$date <= "2024-04-30",
                    "El Niño period",
                    "Other months")

ggpairs(
  df,
  columns = c("air_temp",
              "solar_radiation",
              "precipitation",
              "lst",
              "cooling"),
  diag = list(
    continuous = wrap("densityDiag", alpha = 0.4)
  ),
  upper = list(
    continuous = wrap("cor", size = 3)
  ),
  aes(color = period, shape = period),
  progress = FALSE
)

# check for lst of open land and lst of forest
ggpairs(
  df,
  columns = c("air_temp",
              "solar_radiation",
              "precipitation",
              "forest",
              "open_land",
              "cooling"),
  diag = list(
    continuous = wrap("densityDiag", alpha = 0.4)
  ),
  upper = list(
    continuous = wrap("cor", size = 3)
  ),
  aes(color = period, shape = period),
  progress = FALSE
)


```

## Linear T-air and T-lst

```{r}
ggplot(df, aes(x = lst, y = air_temp)) +
  geom_point() +
  stat_poly_line(formula = y ~ x, color="red", se=FALSE) +
  stat_poly_eq(use_label("eq", "R2"), formula = y ~ x) +
  labs(
      x = "Land surface temperature (°C)",
      y = "Air temperature (°C)"
    )+
  theme_minimal() 
```

## Hottest months

```{r}
full <- read_csv(here("04_output", "lst_and_climate_var_monthly_mean.csv"))

# print the hottest months for open land according to the lst data
hottest <- full |>
  group_by(year)

hottest |> slice_max(t1330, n = 1, with_ties = FALSE) #results 03, 02, 02, 03

hottest |> slice_max(lst_mean, n = 1, with_ties = FALSE) #results 04, 03, 04, 03

hottest |> slice_max(ssrd_Wm2_1330, n = 1, with_ties = FALSE) #results 03, 03, 04, 03

hottest |> slice_max(cooling, n = 1, with_ties = FALSE) #results 04, 04, 03, 04

hottest |> slice_min(precipitation_mm, n = 1, with_ties = FALSE) #results 03, 01, 02, 01

full |>
  filter(
    year == 2021 & month == 12
  ) |> select (precipitation_mm)

hottest |> 
  arrange(precipitation_mm) |>
  slice_head(n=3) |>
  select(date, precipitation_mm) |>
  filter(year != 2020)
  
```

## older Corellation

```{r}
df <- read_csv(here("04_output", "lst_and_climate_var_monthly_mean.csv"))

pairs(df[, c("cooling",
             "lst_mean",
             "t1330",
             "precipitation_mm",
             "ssrd_Wm2_1330")])

cor(df[, c("cooling",
           "lst_mean",
           "t1330",
           "precipitation_mm",
           "ssrd_Wm2_1330")],
    use = "complete.obs")
```

```{r}

# standardize predictors
df <- df |>
  mutate(
    temp_z = scale(t1330),
    precip_z = scale(precipitation_mm),
    radiation_z = scale(ssrd_Wm2_1330)
  )

pairs(df[, c("cooling",
             "lst_mean",
             "t1330",
             "precipitation_mm",
             "ssrd_Wm2_1330")])

cor(df[, c("cooling",
           "lst_mean",
           "t1330",
           "precipitation_mm",
           "ssrd_Wm2_1330")],
    use = "complete.obs")
```

```{r}

model_full <- lm(
  cooling ~ temp_z + precip_z + radiation_z,
  data = df
)

summary(model_full)
```

```{r}

vif(model_full)

```
