---
title: "LST_major_landcovers"
format: html
---

```{r}
library(dplyr)
library(ggplot2)
```

```{r}
day <- read.csv("data/LST_2023_day_100elv.csv")
night <- read.csv("data/LST_2023_night_100elv.csv")

clean <- function(df){
  df$LST_C <- df$LST - 273.15 #convert K to C
  df$land_type <- factor(df$land_type, labels = c('forest', 'palm plantation', 'pineapple', 'low vegetation', 'urban'))
  date_cols <- c("interval_from","interval_to")
  for (col in date_cols) {
    df[[col]] <- as.Date(df[[col]])
  }
  return(df)
}

day <- clean(day)
night <- clean(night)


```

```{r}
day$time <- "day"
night$time <- "night"
day_night <- rbind(day, night)
day_night$time <- factor(day_night$time)
head(day_night)
```

```{r}
plotLST <- function (df)  {
  ggplot(df, aes(x = interval_from, y = LST_C, color = land_type)) +
    # geom_point(alpha = 0.2) +            # optional: show the raw points
    geom_smooth(method = "loess",        # "loess" for local smoothing
                span = 0.1,              # adjust smoothness (0-1)
                se = TRUE) +               # display confidence interval
    scale_colour_manual(
      values = c("darkgreen", "#9a125b", "#E05DD7", "sienna2","#f62024")
    )+
    scale_x_date(date_breaks = "1 month",  date_labels = "%b")+
    scale_y_continuous(limits = c(10, 45), breaks = seq(10, 45, by = 5))+
    labs(x = "Date", y = "LST (C)") +
    theme_bw()+
    theme(axis.text.x = element_text(angle = 90, hjust = 1),
          legend.position = "right",                  
          legend.justification = c("left", "top"),
          legend.title = element_blank())+
    facet_grid(cols = vars(time))
}

p1 <- plotLST(day_night)
```

```{r}
p1
```

```{r}
ggsave("plot1_2.png", plot = p1, width = 18, height = 8, units = "cm", dpi = 300)
```

```{r}

```

```{r}
plotLST <- function (df)  {
  ggplot(df, aes(x = interval_from, y = LST_C, color = land_type)) +
    geom_point(size= 0.5, alpha = 0.05) +            # optional: show the raw points
    geom_smooth(method = "loess",        # "loess" for local smoothing
                span = 0.1,              # adjust smoothness (0-1)
                se = TRUE) +              # display confidence interval
    scale_colour_manual(
      values = c("darkgreen", "#9a125b", "#E05DD7", "sienna2","#f62024")
    )+
    scale_x_date(date_breaks = "2 months",  date_labels = "%b")+
    scale_y_continuous(limits = c(10, 50), breaks = seq(10, 50, by = 5))+
    labs(x = "Date", y = "LST (C)") +
    theme_bw()+
    theme(axis.text.x = element_text(angle = 90, hjust = 1),
          (legend.position = "none"))
          # legend.position = "right",                  
          # legend.justification = c("left", "top"),
          # legend.title = element_blank()) 
}



```

```{r}
p2 <-plotLST(day_night)
p2 <- p2 + facet_grid(vars(time),vars(land_type))+theme(legend.position = "none")
```

```{r}
p2
```

```{r}
ggsave("plot2.png", plot = p2, width = 15, height = 12, units = "cm", dpi = 300)
```
